# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

version: '3.9'

services:

  my-app:
    container_name: my-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=swe304
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres123
      - DB_PORT=5432

  postgres:
    container_name: my-db
    image: postgres:latest
    restart: always
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=swe304
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    volumes:
      - postgres_db:/var/lib/postgresql/data


secrets:
  db-password:
    file: db/password.txt
volumes:
  postgres_db:
