name: Java CI with Gradle and Docker

on:
  workflow_dispatch: 
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build -x test
      
    - name: Build Docker image
      run: docker build . --tag ${{ secrets.DOCKER_USERNAME }}/my-app:${{ secrets.MAJOR }}.0.${{ secrets.MINOR }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ secrets.MAJOR }}.0.${{ secrets.MINOR }}
      
    - name: Update Minor version
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MINOR'
        value: $((${{ secrets.MINOR }} + 1))
        repository: eskhas/my-app
        token: ${{ secrets.REPO_ACCESS_TOKEN }}








